# Stage 1: Build the React app
FROM node:14-alpine as alpineBase

WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install --frozen-lockfile

# Copy the app's source code
COPY . .

# Build the app
RUN yarn build

# Stage 2: Create a lightweight production image
FROM nginx:1.21-alpine

# Copy the built app from the previous stage
COPY --from=alpineBase /app/build /usr/share/nginx/html

# Remove the default nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy a custom nginx configuration
COPY nginx.conf /etc/nginx/conf.d

# Expose port 80
EXPOSE 80

# Start nginx server
CMD ["nginx", "-g", "daemon off;"]
